### ISSUE TITLE
IndexError: list index out of range in `adjustTag`

### ISSUE THREAD

**Issue by eromoe** [thunlp/THULAC-Python#14]
Hi,

thulac 处理某些文本的时会出错

```
Traceback (most recent call last):
  File "test_thulac.py", line 9, in <module>
    tokens = thul.cut(text)
  File "/usr/local/lib/python2.7/dist-packages/thulac/__init__.py", line 90, in cut
    array += (reduce(lambda x, y: x + [y.split(self.separator)], self.cutline(line), []))
  File "/usr/local/lib/python2.7/dist-packages/thulac/__init__.py", line 133, in cutline
    self.punctuation.adjustTag(tagged)
  File "/usr/local/lib/python2.7/dist-packages/thulac/manage/Punctuation.py", line 39, in adjustTag
    tmp = sentence[i][0]
IndexError: list index out of range

```

样本文件:
[测试.txt](https://github.com/thunlp/THULAC-Python/files/798865/default.txt)
[测试2.txt](https://github.com/thunlp/THULAC-Python/files/798867/2.txt)

**Comment by gzp9595** [comment]
非常感谢您对THULAC的支持，我们使用您提供的测试数据进行了测试，并没有出现您所提出的的问题~

不知道您是在什么环境下使用的THULAC，以及怎么进行的测试~

**Comment by MaJunhua** [comment]
感谢您对THULAC的支持，您应该用的是pip版本，我们会在近期尽快更新。在此之前您可以先使用github上的版本

**Comment by eromoe** [comment]
好的，谢谢！
