### ISSUE TITLE
接口使用示例报错：UnicodeDecodeError: 'utf8' codec can't decode byte 0xc4 in position 4: invalid continuation byte

### ISSUE THREAD

**Issue by jamestch** [thunlp/THULAC-Python#16]
Hi,
在运行主页1.1.接口使用示例-代码示例1的时候报错：
Traceback (most recent call last):
  File "test_thulac_POS.py", line 16, in <module>
    thu1.cut_f("input.txt", "output.txt") 
  File "/home/bdsirs/py2env/local/lib/python2.7/site-packages/thulac/__init__.py", line 167, in cut_f
    cutted = self.cut(oiraw, text = True)
  File "/home/bdsirs/py2env/local/lib/python2.7/site-packages/thulac/__init__.py", line 93, in cut
    return self.__cutWithOutMethod(oiraw, self.__cutline, text = text)
  File "/home/bdsirs/py2env/local/lib/python2.7/site-packages/thulac/__init__.py", line 76, in __cutWithOutMethod
    txt += reduce(lambda x, y: x + ' ' + y, cut_method(line)) + '\n'
  File "/home/bdsirs/py2env/local/lib/python2.7/site-packages/thulac/__init__.py", line 99, in __cutline
    oiraw = decode(oiraw, coding = self.__coding)
  File "/home/bdsirs/py2env/local/lib/python2.7/site-packages/thulac/base/compatibility.py", line 4, in decode
    return string.decode('utf-8')
  File "/home/bdsirs/py2env/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc4 in position 4: invalid continuation byte

我已经在py文件的头部加了#encoding=utf-8,但是还是报错。请问这个有什么解决方法吗？

**Comment by jamestch** [comment]
抱歉，我已经找到问题解决方式了。
input.txt编码方式不为utf-8，所以需要转换编码方式
