### ISSUE TITLE
TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by hustlrr** [thunlp/THULAC-Python#18]
`
import thulac
thu = thulac.thulac(seg_only=True)
def thu_segment(sent):
    '''
    :type sent: str
    :return:
    '''
    text = thu.cut(sent, text=True)
    return text  # 返回的编码是UTF-8
if __name__ == '__main__':
    sent = thu_segment(" ")  # 中文空格
    print(sent)
`
I run the above code, then I got following errors:
Traceback (most recent call last):
  File "E:/python/text_classification/preprocess/segment.py", line 35, in <module>
    sent = thu_segment(" ")
  File "E:/python/text_classification/preprocess/segment.py", line 20, in thu_segment
    text = thu.cut(sent, text=True)
  File "D:\Python27\lib\site-packages\thulac\__init__.py", line 97, in cut
    return self.__cutWithOutMethod(oiraw, self.__cutline, text = text)
  File "D:\Python27\lib\site-packages\thulac\__init__.py", line 80, in __cutWithOutMethod
    txt += reduce(lambda x, y: x + ' ' + y, cut_method(line)) + '\n'
I think that you should add an initial value in the reduce function to solve the problem. THX~

**Comment by MaJunhua** [comment]
Thanks for your issue! We have fixed this bug.
