### ISSUE TITLE
Python Demo MemoryError错误

### ISSUE THREAD

**Issue by ZhiyuanLIPlus** [thunlp/THULAC-Python#19]
您好，
感谢你们的分享！知道THULAC出了PYTHON 版本之后第一时间就过来尝试了一下。
但是在运行代码时候， 出现了以下错误。
```
Traceback (most recent call last):
  File "D:\Software\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Software\PyCharm Community Edition 2016.3.2\helpers\pydev\pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/Documents/Projects/TangPoetryAnalyzer/test.py", line 4, in <module>
    thu1 = thulac.thulac()  #默认模式
  File "D:\Software\Python27\lib\site-packages\thulac\__init__.py", line 58, in __init__
    self.__tagging_decoder.init((self.__prefix+"model_c_model.bin"),(self.__prefix+"model_c_dat.bin"),(self.__prefix+"model_c_label.txt"))
  File "D:\Software\Python27\lib\site-packages\thulac\character\CBTaggingDecoder.py", line 36, in init
    self.model = CBModel(modelFile)
  File "D:\Software\Python27\lib\site-packages\thulac\character\CBModel.py", line 58, in __init__
    self.fl_weights = struct.unpack("<"+str(self.f_size * self.l_size)+"i", temp)
MemoryError
```

我看了下报错行是在CBModel.py中的__init__：
```python
self.fl_weights = struct.unpack("<"+str(self.f_size * self.l_size)+"i", temp)
```
我的测试代码是test.py
```python
# -*- coding: utf-8 -*-
import thulac

thu1 = thulac.thulac()  #默认模式
text = thu1.cut("我爱北京天安门", text=True)  #进行一句话分词
print(text)
```
我的OS是Windows 10，安装命令是WIN命令行使用的pip install thulac. 版本号是Successfully installed thulac-0.1.1
IDE是PYCHARM，但是我尝试使用命令行编译依然会出现同样错误。

我尝试过的方法有：
1. uninstall再install
2. 命令行编译
3. 网上寻找相关报错未果

但是都没能找到解决方案，因此发布了一个issue希望能够得到您的帮助，谢谢！

**Comment by ZhiyuanLIPlus** [comment]
Update: 
将CBModel.py, cws_model.bin, model_c_model.bin拷进自己的workplace.

编译CBModel.py出错
将__main__改为
```python
if __name__ == '__main__':
    mod = CBModel("cws_model.bin")
    print(len(mod.fl_weights))
```
编译成功

这样看来似乎是本机加载model的问题

**Comment by ZhiyuanLIPlus** [comment]
再次Update：
test.py
```python
# -*- coding: utf-8 -*-
import thulac

thu1 = thulac.thulac(seg_only=True)  #默认模式
text = thu1.cut("我爱北京天安门", text=True)  #进行一句话分词
print(text)
```

编译通过，运行成功。

是否是在不进行词性标注的时候所使用的model就不一样了呢？

**Comment by gzp9595** [comment]
您好，非常感谢对THULAC的支持
我们只分词和分词加词性标注使用的是不同的模型，可能对于分词加词性标注的模型需要的内存会表较大，所以从出现的错误上看，可能会因为没有办法把模型读入内存造成的~

**Comment by ZhiyuanLIPlus** [comment]
您好，谢谢您的答复。
今天将PYTHON版本从2.7更新到了3.6，就没有这个问题了。只分词和分词加词性标注都可以编译成功。
还是谢谢您的回复了~
