### ISSUE TITLE
请明示安装方法

### ISSUE THREAD

**Issue by fanzhen1** [thunlp/THULAC-Python#2]
文科生学文本挖掘见笑。。。。。

说明文件只提到“将thulac放到目录下，通过 import thulac 来引用”，通过几次测试，我把thulac文件放在了Python安装目录lib文件下，在Python35 import成功，但是主页提供的命令不可用，后来注意到thulac只支持Python2环境，于是换了Python27 。以同样的方式复制到lib文件夹却无法import。idle的提示是：

>>> import thulac

Traceback (most recent call last):
File "<pyshell#0>", line 1, in <module>
import thulac
File "E:\Python27\lib\thulac\__init__.py", line 4, in <module>
from character.CBTaggingDecoder import CBTaggingDecoder
File "E:\Python27\lib\thulac\character\CBTaggingDecoder.py", line 10, in <module>
import numpy
ImportError: No module named numpy

系统环境win10 64bit，Python2.7.12 32bit

**Comment by huangshenno1** [comment]
说明还需要另外装numpy。
建议项目作者把相关依赖都写到README里一下。

**Comment by xchuwenbo** [comment]
我也想知道model文件如何安装。。。
