### ISSUE TITLE
thu1 = thulac.thulac()  memory error

### ISSUE THREAD

**Issue by HappyShadowWalker** [thunlp/THULAC-Python#25]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\thulac\__init__.py", line 58, in __init__
    self.__tagging_decoder.init((self.__prefix+"model_c_model.bin"),(self.__prefix+"model_c_dat.bin"),(self.__prefix+"model_c_label.txt"))
  File "C:\Python27\lib\site-packages\thulac\character\CBTaggingDecoder.py", line 36, in init
    self.model = CBModel(modelFile)
  File "C:\Python27\lib\site-packages\thulac\character\CBModel.py", line 58, in __init__
    self.fl_weights = struct.unpack("<"+str(self.f_size * self.l_size)+"i", temp)
MemoryError

**Comment by MaJunhua** [comment]
感谢您对thulac的支持，由于我们之前的开发没有针对windows进行，所以Windows上面python2.7兼容目前有些问题。不过从之前的反馈来看，windows上python3.6不会有这个问题

**Comment by PaniniGelato** [comment]
编辑CBModel.py，找到__init__方法，找到下面这个代码：

```python
temp = inputfile.read(4 * self.f_size * self.l_size)
self.fl_weights = struct.unpack("<"+str(self.f_size * self.l_size)+"i", temp)
```

改成
```python
self.fl_weights = array.array('i')
self.fl_weights.fromfile(inputfile, self.f_size * self.l_size)
```

再加上import
```python
import array
```

python2.7适用，3.6有这个API，也能兼任

**Comment by Pacific73** [comment]
PaniniGelato's answer works for me on windows. Python 2.7.13.

**Comment by LiXiaoB** [comment]
PaniniGelato's answer saved ~330MB when initialize thulac, python 2.7

**Comment by KisAaki** [comment]
python3.6，仍然出现了上述问题；采用了[PaniniGelato](https://github.com/PaniniGelato)的方法后同样会出现
