### ISSUE TITLE
Pycharm 等IDE中无法导入thulac

### ISSUE THREAD

**Issue by jinfagang** [thunlp/THULAC-Python#26]
非常感谢创作这个中文分词包，并且自带词性识别，不过好像在Pycharm ide中无法导入thulac，在terminal里面可以，不知为何，同志们可以测试一下

**Comment by MaJunhua** [comment]
我们开发的时候也会用pycharm调试啊，好像没有问题？

**Comment by hellopiece** [comment]
我也遇到了这个问题。
错误信息：
Traceback (most recent call last):
  File "D:/Programing/Python/pycharm/cifar/thulac.py", line 3, in <module>
    import thulac
  File "D:\Programing\Python\pycharm\cifar\thulac.py", line 5, in <module>
    thu1 = thulac.thulac()
TypeError: 'module' object is not callable

thulac警告信息：Import resolves to its containing file less... (Ctrl+F1) 
This inspection detects names that should resolve but don't. Due to dynamic dispatch and duck typing, this is possible in a limited but useful number of cases. Top-level and class-level items are supported better than instance items.
