### ISSUE TITLE
分词后返回byte字符

### ISSUE THREAD

**Issue by 363325971** [thunlp/THULAC-Python#33]
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import thulac
>>> thu = thulac.thulac()
Model loaded succeed
>>> thu.cut('我们中出了一个叛徒')
[['\xe6\x88\x91\xe4\xbb\xac', 'r'], ['\xe4\xb8\xad', 'f'], ['\xe5\x87\xba', 'v'], ['\xe4\xba\x86', 'u'], ['\xe4\xb8\x80\xe4\xb8\xaa', 'm'], ['\xe5\x8f\x9b\xe5\xbe\x92', 'n']]
>>> 

cut后返回的list里的中午变成byte字符，求解，，我看别人用的都是好好的

**Comment by wangzhe258369** [comment]
同发现了。cut函数返回的字符串类型为str（Python 2），不是unicode，这样挺不好的。

**Comment by MaJunhua** [comment]
谢谢您对THULAC的支持，python2中直接打印list的话其中的中文确实会变为byte字符，语句print ["我"]也会有相同的效果。需要看文字结果可以使用cut(text=True)哈。

**Comment by zyb8543d** [comment]
>>> text = thu1.cut("我爱北京天安门", text=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\thulac\__init__.py",
line 107, in cut
    return self.__cutWithOutMethod(oiraw, self.__cutline, text = text)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\thulac\__init__.py",
line 91, in __cutWithOutMethod
    temp_txt = reduce(lambda x, y: x + ' ' + "".join(y), cut_method(line), '') +
 '\n'
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\thulac\__init__.py",
line 114, in __cutline
    oiraw = decode(oiraw)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\thulac\base\compatibi
lity.py", line 10, in <lambda>
    return lambda s: s.decode('utf-8')
  File "C:\Users\Administrator\Anaconda2\lib\encodings\utf_8.py", line 16, in de
code
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xce in position 0: invalid c
ontinuation byte
