### ISSUE TITLE
python的demo运行报错

### ISSUE THREAD

**Issue by andychao95** [thunlp/THULAC-Python#4]
您好，我尝试用python导入THULAC包来完成一项中文分词任务。但是，在pycharm编译器里连demo都运行不了，请问一下这是怎么回事呢？

完整报错反馈如下：

`/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/andychao/Downloads/THULAC-Python-master/demo.py
Traceback (most recent call last):
  File "/Users/andychao/Downloads/THULAC-Python-master/demo.py", line 5, in <module>
    thu1 = thulac.thulac("-seg_only")  #设置模式为行分词模式
  File "/Users/andychao/Library/Python/2.7/lib/python/site-packages/thulac/__init__.py", line 68, in __init__
    self.cws_tagging_decoder.init((self.prefix+"cws_model.bin"), (self.prefix+"cws_dat.bin"),(self.prefix+"cws_label.txt"))
  File "/Users/andychao/Library/Python/2.7/lib/python/site-packages/thulac/character/CBTaggingDecoder.py", line 36, in init
    self.model = CBModel(modelFile)
  File "/Users/andychao/Library/Python/2.7/lib/python/site-packages/thulac/character/CBModel.py", line 55, in __init__
    inputfile = open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/Users/andychao/Library/Python/2.7/lib/python/site-packages/thulac/models/cws_model.bin'

Process finished with exit code 1`

**Comment by gzp9595** [comment]
您好，感谢您对THULAC的使用和支持，我们的程序需要分词和词性标注的模型支持，这个是需要另外下载的，当然也是免费的，下载地址和说明在刚刚更新的README中有说明，您也可以登陆我们的网站thulac.thunlp.org查看

**Comment by andychao95** [comment]
您好，其实我作为一个新手还是没太懂您说的。我是Mac电脑，下载了THULAC_lite_python_v1和THULAC-Python-master两种压缩包，里面的内容都是cs.txt、demo.py、README.md和thulac文件夹。我以前是把thulac文件夹移到
/Users/andychao/Library/Python/2.7/lib/python/site-packages/  
里面去，在这里可以顺利的import。但是我没有明白，您说还差的东西是指的什么？需要我移到哪里去？

**Comment by gzp9595** [comment]
你好，是这样的，网站上下载的和这里的都是一样的代码，我们的工具是需要models支持的，这两个是分开下载的，您的报错是因为缺少模型文件造成的。
您需要再下载模型文件，并且放到THULAC文件夹中，就可以运行demo.py文件

**Comment by andychao95** [comment]
您好，我按照您所说的运行后，返回结果没有报错了。但是demo运行结果只有Model loaded succeed，没有输出分词结果。请问一下这是怎么一回事？麻烦了！

**Comment by gzp9595** [comment]
你可以看一下demo.py的注释，是从屏幕输入、然后屏幕输出结果～
程序是有对应的注释的～
