### ISSUE TITLE
fast_text() 报错：list index out of range

### ISSUE THREAD

**Issue by kaiyu-tang** [thunlp/THULAC-Python#75]
输入str 为：
"     完赛  客观来说 切尔西今天比赛的场面并不是很好看 但拿到三分比什么都重要 另外 让穆帅感到欣慰的是核心阿扎尔状态的回升 比利时人今天的突破非常犀利 "

错误详细为：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/atlab/Softwares/anaconda3/envs/kaiyu-demo/lib/python3.6/site-packages/thulac/__init__.py", line 110, in fast_cut
    return self.__cutWithOutMethod(oiraw, self.__fast_cutline, text = text)
  File "/home/atlab/Softwares/anaconda3/envs/kaiyu-demo/lib/python3.6/site-packages/thulac/__init__.py", line 100, in __cutWithOutMethod
    array += (reduce(lambda x, y: x + [[y[0], y[2]]], cut_method(line), []))
  File "/home/atlab/Softwares/anaconda3/envs/kaiyu-demo/lib/python3.6/site-packages/thulac/__init__.py", line 100, in <lambda>
    array += (reduce(lambda x, y: x + [[y[0], y[2]]], cut_method(line), []))
IndexError: list index out of range

**Comment by LabroShine** [comment]
我也遇到了相似的问题，很奇怪～
