### ISSUE TITLE
找不到指定的模块

### ISSUE THREAD

**Issue by JungleXia** [thunlp/THULAC-Python#89]

**Comment by JungleXia** [comment]
D:\ProgramData\Anaconda3\envs\pyppeteer\python.exe F:/Pywork/pyppe/agent_pyq/test_thulac.py
Traceback (most recent call last):
  File "F:/Pywork/pyppe/agent_pyq/test_thulac.py", line 14, in <module>
Model loaded succeed
    """, "output_thulac.txt")  # 对input.txt文件内容进行分词，输出到output.txt
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\site-packages\thulac\__init__.py", line 110, in fast_cut
    return self.__cutWithOutMethod(oiraw, self.__fast_cutline, text = text)
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\site-packages\thulac\__init__.py", line 89, in __cutWithOutMethod
    temp_txt = reduce(lambda x, y: x + ' ' + y if y != " " else x, cut_method(line), '') + '\n'
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\site-packages\thulac\__init__.py", line 170, in __fast_cutline
    self.__so = self.__SoInit()
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\site-packages\thulac\__init__.py", line 166, in __SoInit
    return SoExtention(self.__prefix, self.__user_specified_dict_name, self.__useT2S, self.__seg_only)
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\site-packages\thulac\manage\SoExtention.py", line 13, in __init__
    self._lib = cdll.LoadLibrary(root+'/libthulac.so') #读取so文件
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
