### ISSUE TITLE
fast_cut 运行错误：OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by JungleXia** [thunlp/THULAC-Python#90]
D:\ProgramData\Anaconda3\envs\pyppeteer\python.exe F:/Pywork/pyppe/agent_pyq/test_thulac.py
F:\Pywork\pyppe\agent_pyq
Traceback (most recent call last):
  File "F:/Pywork/pyppe/agent_pyq/test_thulac.py", line 47, in <module>
    thu1 = ThulacSo()  # 模型等文件预读取和初始化
  File "F:/Pywork/pyppe/agent_pyq/test_thulac.py", line 23, in __init__
    self.lib = cdll.LoadLibrary('F:/Pywork/pyppe/agent_pyq/libthulac.so')  # 读取so文件
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "D:\ProgramData\Anaconda3\envs\pyppeteer\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by MaJunhua** [comment]
fask_cut目前不支持windows哈
